filebeat.inputs:
  - type: filestream
    paths:
      - /var/log/kibana.log
    parsers:
      - ndjson:
          keys_under_root: true
          overwrite_keys: true
          add_error_key: true
          message_key: message

output.elasticsearch.index: "filebeat-reporting-%{[agent.version]}"
setup.template.name: "filebeat-reporting"
setup.template.pattern: "filebeat-reporting-%{[agent.version]}"

setup.template.settings:
  index.number_of_shards: 1
  index.codec: best_compression

setup.template.append_fields:
  - name: kibana.reporting.id
    type: keyword
  - name: kibana.task.id
    type: keyword

  - name: kibana.reporting.jobType
    type: keyword
  - name: kibana.reporting.actionType
    type: keyword

  - name: kibana.reporting.byteSize
    type: long

  - name: kibana.reporting.csv.rows
    type: long
  - name: kibana.reporting.csv.fields
    type: long

  - name: kibana.reporting.png.cpu
    type: long
  - name: kibana.reporting.png.cpuInPercentage
    type: long
  - name: kibana.reporting.png.memoryInMegabytes
    type: long

  - name: kibana.reporting.pdf.cpu
    type: long
  - name: kibana.reporting.pdf.cpuInPercentage
    type: long
  - name: kibana.reporting.pdf.memoryInMegabytes
    type: long
  - name: kibana.reporting.pdf.pages
    type: long

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  protocol: "http"
  username: "elastic"
  password: "changeme"
