server.host: 0.0.0.0

elasticsearch:
  username: "kibana_system"
  password: "changeme"
  hosts: ['http://elasticsearch:9200']

xpack.reporting:
  encryptionKey: MjAxOC0wOS0yMFQxODo0ODowNlogMjAxODA5MjBfMTg0OCAxNTM3NDY5Mjg2NzQx
  roles.enabled: false
  csv.maxSizeBytes: 500000000
  capture.maxAttempts: 1
  capture.timeouts:
    renderComplete: 1m
    waitForElements: 1m


logging:
  appenders.file:
    type: file
    fileName: /var/log/kibana.log
    layout.type: json
  root.appenders: [console,file]
  loggers:
    - name: plugins.screenshotting
      level: debug
    - name: plugins.reporting
      level: debug
    - name: metrics.ops
      level: debug
