server.host: 0.0.0.0

elasticsearch:
  username: "kibana_system"
  password: "changeme"
  hosts: ['http://elasticsearch:9200']

logging:
  appenders:
    file:
      type: file
      fileName: logs/kibana.log
      layout:
        type: json
  root:
    appenders: [file]
  loggers:
    - name: plugins.reporting
      appenders: [file]
      level: debug
    - name: plugins.screenshotting
      appenders: [file]
      level: debug
    - name: metrics.ops
      appenders: [file]
      level: debug

xpack.reporting:
  encryptionKey: MjAxOC0wOS0yMFQxODo0ODowNlogMjAxODA5MjBfMTg0OCAxNTM3NDY5Mjg2NzQx
  roles.enabled: false
  csv.maxSizeBytes: 500000000
  capture.maxAttempts: 1
  capture.timeouts:
    renderComplete: 1m
    waitForElements: 1m
