server.host: 0.0.0.0

elasticsearch:
  username: "kibana_system"
  password: "changeme"
  hosts: ['http://elasticsearch:9200']

logging:
 loggers:
   - name: plugins.screenshotting
     appenders: [console]
     level: debug
   - name: plugins.reporting
     appenders: [console]
     level: debug

xpack.reporting:
  encryptionKey: MjAxOC0wOS0yMFQxODo0ODowNlogMjAxODA5MjBfMTg0OCAxNTM3NDY5Mjg2NzQx
  roles.enabled: false
  csv.maxSizeBytes: 500000000
  capture.maxAttempts: 1
  capture.timeouts:
    renderComplete: 1m
    waitForElements: 1m
