http.enabled: true
http.port: 5067
monitoring.enabled: false

metricbeat:
  config.modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false
  modules:
  - module: kibana
    metricsets: ["status"]
    period: 10s
    hosts: ["localhost:5601"]
    enabled: true
    username: "kibana_system"
    password: "changeme"

setup.template.settings:
  index.number_of_shards: 1
  index.codec: best_compression
setup.kibana:
  host: "localhost:5601"
output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  ssl.certificate_authorities: ["/vagrant/share/config/cert-bundle/ca/ca.crt"]
  protocol: "https"
  username: "elastic"
  password: "changeme"
processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~


